### ISSUE TITLE
Question: Calculate the expected duration of a TKperf run?

### ISSUE THREAD

**Issue by fthommen** [thomas-krenn/TKperf#38]
Hi,

Is there a way to establish beforehand how long a TKperf will run?

I've started a test run according to https://www.thomas-krenn.com/de/wiki/TKperf#Testlauf_starten on a (virtual) 512GB SSD within a virtualization environment.  After almost 24h it has only done the "lat" test and is currently running the "writesat" test.  Is this an expected duration?

**Comment by tniedermeier** [comment]
Hi @fthommen,

thanks for your question, yes indeed tests of large SSD literally take forever, you have to be very patient...
I don't know such an indicator how long the test will take.
But you can limit the runtime of each test: Parameter -rt 30 limits each test to 30 seconds instead of 60 seconds.
When we run tests on really large SSDs, we limit the runtime of each test with this parameter.

Best regards,
Thomas

**Comment by fthommen** [comment]
Thank you.  That helped :-)
